### ISSUE TITLE
ocramius (proxy-manage)

### ISSUE THREAD

**Issue by remadrivan** [HackThisCode/CryptoPaste#17]
Hi, I would like to ask why you added this library...

Is it backdoored?

**Comment by Kage** [comment]
What library are you referring to? Neither `ocramius` nor `proxy-manage` nor anything related appear anywhere in the source code. Are you sure you're commenting on the right GitHub project?

**Comment by remadrivan** [comment]
yes, I'm sure because I have tried cloning the project and running it on my localhost but it's not working

**Comment by Kage** [comment]
Can you please give more details about how it's not working, like error logs or something?  Also please give more information about what you meant about using [ocramius/proxy-manager](https://github.com/Ocramius/ProxyManager), because that's not used in this project.  I won't be able to help you without more context and details.

**Comment by remadrivan** [comment]
I tried a clean installation on your script but it's not working.. lots of errors and it's not working on my localhost...
