### ISSUE TITLE
[Feature Request] Allow pastes without a password

### ISSUE THREAD

**Issue by d1str0** [HackThisCode/CryptoPaste#5]
I can see users wanting to share pastes that don't require a password. Not everything should be required to be encrypted IMO. This would also let users view a paste immediately without decrypting.

Maybe a single warning on submit that tells users they haven't entered a pass key?

**Comment by Kage** [comment]
I must reject because the entire point is to store _only_ encrypted content. The objective is twofold here:
1. Plausible Deniability for the host
2. Lack of undue responsibility for the host (no need to moderate, adhere to new GDPR requirements, etc.)

If someone wants to paste without a password, https://pastebin.com is good enough.
